### ISSUE TITLE
Multiple Icebreakers

### ISSUE THREAD

**Issue by nalhemyariirexorg** [OfficeDev/microsoft-teams-apps-icebreaker#111]
Hello, first thanks for Icebreaker, we enjoy it a lot and for that we have requests to expand beyond my team.

Currently I have modified the logic app to run once a month (works better for my team size), yet I have 2 new teams interested in Icebreaker in team but want to meet up once a week (the default setup), how can I achieve this? should I run the full deployment again, or are there some component I can duplicate in Azure to have a different schedule?

**Comment by chartaam** [comment]
We also need to have different Teams have different notification schedules and frequencies. I would love to know how to do this.

**Comment by nalhemyariirexorg** [comment]
@chartaam I ended up deploying the entire product once again using a different azure resource group 'to avoid conflict' using a different name IceB_Weekly, IceB_BiWeekly then changed the logic app trigger for the desired schedule. I hope this helps

**Comment by Office365-LUMC** [comment]
@nalhemyariirexorg Hi we also tried your solution (different Resource group, different Azure App registration, different Github code (because different look and feel), different name, etcetera. But when we try to add it to Teams, we receive a message that the app is already in the Teams Catalog. 

Did you have the same problem and how did you resolved that? Or do you know any solution for us? 

Thanks in advance, 
Sander

**Comment by nalhemyariirexorg** [comment]
@Office365-LUMC I had to change the app name in the xml app before uploading to Teams admin center

**Comment by Office365-LUMC** [comment]
@nalhemyariirexorg  Hi, do you mean the Short Name in Manifest.json? Because we upload only these three files"in a ZIP file: color.png, manifest.json and outline.png

**Comment by nalhemyariirexorg** [comment]
> @nalhemyariirexorg Hi, do you mean the Short Name in Manifest.json? Because we only upload these three files in a ZIP file: color.png, manifest.json and outline.png

Yes, my apologies for the confusion

**Comment by PramodDeokar-ms** [comment]
You also need to change _id_ to new GUID in manifest.json

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by chartaam** [comment]
I am not the original poster -- but I would love to see some work done on this issue. It is too complicated, the way it is now -- where if you want bots running on different schedules, you have to stand multiples up and jump through the right hoops.

**Comment by cgjeb** [comment]
> You also need to change _id_ to new GUID in manifest.json

What id do you mean? 
We have multiple icebreakers for different teams and running on separate schedules, initially deployed by someone else.

I've just deployed another icebreaker bot for another team, followed that guide
https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Deployment-Guide-manual, but it does not explain anything on multiple icebreaker deployments.

All I did was to change the "App Name" field in the deployment template from icebreaker to something else e.g. icebreaker-FYI (This is because I was using the same resource group and didn't want to cause conflicts with previous deployments).

However, I didn't change that field in the manifest json file "name":  "short": "Icebreaker", I left it as it, however, the sideloading to the teams channel kept failing, until I added all the language files into the zip.

The app is now deployed, and got the notification in the channel, I've modified the schedule via the logic app settings https://blog.thoughtstuff.co.uk/2019/07/how-to-adjust-the-pairing-schedule-of-the-icebreaker-bot-teams-app-template/

I will wait and see if on the scheduled day, the bot will pair users.

**Comment by gsv022** [comment]
HI @nalhemyariirexorg ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to close the long pending issues with no resolution/responses. You may always open a new issue if you are still facing the issue. We are closing this request. Thank you!

**Comment by catietcatie** [comment]
I just wanted to add my 2 cents here.

I have successfully just deployed 1 monthly and 1 weekly Icebreaker apps through manual deployment. 

In this portion of the manifest.json, I had to change the ID, or else it kept telling me I already have this app. In this case, I only changed one letter at the end. This is the original ID.
"$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "1.0.0",
  "id": "d55d08d9-bacb-4567-942f-afd85d632dcc",  (I CHANGED ONE OF THE C's to a F)
  "packageName": "com.microsoft.teams.icebreaker",

*I also changed the Short Name on the 2nd app to match, such as Icebreaker Monthly
*You must also include ALL of the language packs in the zip file before it will actually deploy to a Team. You can upload the app without the language packs, but it won't work.
