### ISSUE TITLE
Getting "manifest parsing has failed" when uploading to Teams

### ISSUE THREAD

**Issue by kstario** [OfficeDev/microsoft-teams-apps-icebreaker#141]
zip package attached. Any ideas?
[package.zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/6093842/package.zip)

Thanks

**Comment by MemoryThulani** [comment]
Hi @kstario. The reason why the manifest failed parsing is because the websiteUrl, privacyUrl and termsOfUseUrl are invalid. I have updated them for you but feel free to replace them. Also, check out this link for reference: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema
[package.zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/6095575/package.zip)

**Comment by kstario** [comment]
Thank you for taking the time to respond. I originally had “company.com” but that did not work either, so I am glad it was just a syntax issue.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
