### ISSUE TITLE
Display name in card 

### ISSUE THREAD

**Issue by krwilson-msft** [OfficeDev/microsoft-teams-apps-icebreaker#185]
In the bot match message we see the text "Hi this is <bot name>". That bot name appears to be taken from the Resource Group name and not the App display name in the paramters.json file as documented.  I have since updated the bot display name in the bot configuration and reimported the app to Teams but the match card still states the Resource Group Name:

![Screenshot 2021-07-06 1615551](https://user-images.githubusercontent.com/80262713/124625405-ab374c80-de75-11eb-9369-97f9c35a2c1b.png)
![Screenshot 2021-07-06 1617152](https://user-images.githubusercontent.com/80262713/124625426-aecad380-de75-11eb-94fc-fd37e0b64c0d.png)

Is there any way to change this name within the card without deploying teh whole solution again?

**Comment by SnappyFPV** [comment]
Same Issue here

**Comment by Porkai-Pandian** [comment]
Bot name can be updated as below,

navigate to your Resource group -> App Service -> Configuration -> update the value for ‘BotDisplayName’ and restart the app service

![image](https://user-images.githubusercontent.com/87537966/181425866-dcc67b49-17b8-4ad1-b4a3-99c6882654c7.png)

Closing the issue since we've provided the necessary solution, kindly open new issue in case of any other queries.
