### ISSUE TITLE
What are valid values for pairingTimeZone?

### ISSUE THREAD

**Issue by TCM69** [OfficeDev/microsoft-teams-apps-icebreaker#223]
If I change default value 'Pacific Standard Time' to 'Central European Time' deployment fails saying that 'Central European Time' is not an valid value. Should I use CET?

**Comment by Porkai-Pandian** [comment]
Hi @TCM69,

Thank you for raising the query here, please don't change the time zone during the deployment as it is the default time zone. However, you can modify the time zone in the Logic Apps that gets created so that the bot pairs in the mentioned time zone. Please let us know if you need more information so that I can share it accordingly.

**Comment by TCM69** [comment]
Many thanks @Porkai-Pandian 
This works as expected. Possibly this could make it into the deployment guides as well as this is currently somewhat misleading where you believe its ok to make changes for pairingTimeZone in the deployment manifest.
