### ISSUE TITLE
Deploy location issue

### ISSUE THREAD

**Issue by tommyoo2** [OfficeDev/microsoft-teams-apps-icebreaker#253]
may I ask whether we support deploy the ice breaker app by suing a southeast Asia resource group?

**Comment by tommyoo2** [comment]
you could refer this ticket (company communicator app) to see what actually happened? it seems cx meet the same issue while they deploy ice breaker and company communicator app 

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/805

**Comment by v-royavinash** [comment]
@tommyoo2, The deployment issue is not specific to company communicator or Icebreaker or any of the apps. Its because of the subscription not allowing app service plan creation in Southeast Asia region. We recommend to raise a Azure Support ticket and check with them if the subscription specific quota has to be increase or any other resolution steps.  

If you go to Azure portal and try creating an App Service Plan for  Southeast Asia region, you will observe same error. Azure support team will be the right team to help you out on this. 

Please refer below link to raise a Azure Support Ticket from Azure portal : https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
